name: CI/CD SafeBase with GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  IMAGE_NAME: safebase

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer PHP + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 3. Lancer les tests Laravel
      - name: Run Laravel tests
        run: php artisan test

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Connexion à GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest .

      # 4. Pousser l'image sur GHCR
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
